// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfievYj-eHHUioAbzYCvTaw9WoSQg8fAA',
    appId: '1:242419823114:web:e38e96e95ca362298165f3',
    messagingSenderId: '242419823114',
    projectId: 'my-firebase-project-3f02d',
    authDomain: 'my-firebase-project-3f02d.firebaseapp.com',
    storageBucket: 'my-firebase-project-3f02d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiufatCs8xbqAUlSJQXbYrqNCjXl36hGg',
    appId: '1:242419823114:android:45b75fa07fe140b68165f3',
    messagingSenderId: '242419823114',
    projectId: 'my-firebase-project-3f02d',
    storageBucket: 'my-firebase-project-3f02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB78pBcU1cbCsZlYM2UJ7mGsOcVp3yQKCw',
    appId: '1:242419823114:ios:bfa513118f8730e78165f3',
    messagingSenderId: '242419823114',
    projectId: 'my-firebase-project-3f02d',
    storageBucket: 'my-firebase-project-3f02d.appspot.com',
    iosClientId:
        '242419823114-9ue9r0gce7jnm44j224mnljgc115l2ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxPlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB78pBcU1cbCsZlYM2UJ7mGsOcVp3yQKCw',
    appId: '1:242419823114:ios:bfa513118f8730e78165f3',
    messagingSenderId: '242419823114',
    projectId: 'my-firebase-project-3f02d',
    storageBucket: 'my-firebase-project-3f02d.appspot.com',
    iosClientId:
        '242419823114-9ue9r0gce7jnm44j224mnljgc115l2ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxPlayground',
  );
}
